
project_id = "ezyngxcqvmuljfkmgjgs"

[functions.create-checkout]
verify_jwt = false

[functions.submit-completed-task]
verify_jwt = true

[functions.verify-task]
verify_jwt = false

[functions.webhook-handler]
verify_jwt = false
